export EXEC_DEVICE	= kartetBasicTestDevice
export EXEC_HOST	= kartetBasicTestHost
export FILES		= main.cu ../Common/GetArgs.cpp
export KARTET_OPTIONS	= -D KARTET_USE_ATLAS
export CC_EXTRA_INCLUDE	= -I../Common/
all :
% :
	@$(MAKE) -s -f $(KARTET_PATH)/Tools/Makefile $@
